{
 "title": "Bitbucket DB Ops",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active connections",
   "type": "timeseries",
   "description": "Active Connections (in use)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_zaxxer_hikari_Pool_bitbucket_ActiveConnections{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Active connections ({{ pod }})"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "description": "Idle Connection count",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_zaxxer_hikari_Pool_bitbucket_IdleConnections{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Idle connections ({{ pod }})"
    }
   ]
  },
  {
   "title": "Threads awaiting connections",
   "type": "timeseries",
   "description": "The number of threads waiting for a connection (when all available connections are in use)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_zaxxer_hikari_Pool_bitbucket_ThreadsAwaitingConnection{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Threads awaiting connections ({{ pod }})"
    }
   ]
  },
  {
   "title": "Total connections ",
   "type": "timeseries",
   "description": "Total Connections",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_zaxxer_hikari_Pool_bitbucket_TotalConnections{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Total connections ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate query cache hit count",
   "type": "timeseries",
   "description": "Global number of cached queries successfully retrieved from cache",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(org_hibernate_core_bitbucket_core_QueryCacheHitCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Query cache hit ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate second level query cache hit count",
   "type": "timeseries",
   "description": "Global number of cacheable entities/collections successfully retrieved from the cache",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(org_hibernate_core_bitbucket_core_SecondLevelCacheHitCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Second level query cache hit ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate query cache miss count",
   "type": "timeseries",
   "description": "Global number of cached queries not found in cache",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(org_hibernate_core_bitbucket_core_QueryCacheMissCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Query cache miss ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate second level query cache miss count",
   "type": "timeseries",
   "description": "Global number of cacheable entities/collections not found in the cache and loaded from the database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(org_hibernate_core_bitbucket_core_SecondLevelCacheMissCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx\"}[5m])",
     "legendFormat": "{{name}} Second level query cache miss ({{ pod }})"
    }
   ]
  }
 ]
}