{
 "title": "Bitbucket Git Operations",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clone request count",
   "type": "timeseries",
   "description": "Number of clone requests served over HTTP and SSH",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneRequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneRequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH ({{ pod }})"
    }
   ]
  },
  {
   "title": "Cloned bytes read & written to clients ",
   "type": "timeseries",
   "description": "Bytes read from clients during clone operations",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP bytes written ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH bytes written ({{ pod }})"
    }
   ]
  },
  {
   "title": "Total number of requests served",
   "type": "timeseries",
   "description": "Total number of requests served",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_RequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_RequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH ({{ pod }})"
    }
   ]
  },
  {
   "title": "Total bytes read & written to clients",
   "type": "timeseries",
   "description": "Total bytes read and written",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_TotalBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "HTTP bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_TotalBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "SSH bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_TotalBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "HTTP bytes written ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_TotalBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "SSH bytes written ({{ pod }})"
    }
   ]
  },
  {
   "title": "Clone cache hit, miss & bypass count",
   "type": "timeseries",
   "description": "HTTP and SSH Clone requests that could not be served from the scm-cache",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheMiss{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP miss ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneCacheMiss{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH miss ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheHit{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP hit ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_CloneCacheHit{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH hit ({{ pod }})"
    },
    {
     "expr": "com_atlassian_bitbucket_HttpHostingStatistics_CloneCacheBypass",
     "legendFormat": "{{name}} HTTP bypass ({{ pod }})"
    },
    {
     "expr": "com_atlassian_bitbucket_SshHostingStatistics_CloneCacheBypass",
     "legendFormat": "{{name}} SSH bypass ({{ pod }})"
    }
   ]
  },
  {
   "title": "Fetch request count",
   "type": "timeseries",
   "description": "Number of fetch requests served\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchRequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchRequestCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH ({{ pod }})"
    }
   ]
  },
  {
   "title": "Fetched bytes read and written to clients",
   "type": "timeseries",
   "description": "Bytes read and written from clients during fetch operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchBytesRead{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH bytes read ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_HttpHostingStatistics_FetchBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} HTTP bytes written ({{ pod }})"
    },
    {
     "expr": "increase(com_atlassian_bitbucket_SshHostingStatistics_FetchBytesWritten{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} SSH bytes written ({{ pod }})"
    }
   ]
  }
 ]
}