{
 "title": "Bitbucket Overview",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{namespace=\"$namespace\", service=\"$service\"}/1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=\"$namespace\", service=\"$service\", state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Repositories Count",
   "type": "timeseries",
   "description": "Count Number of repositories currently configured across all projects.",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(1, com_atlassian_bitbucket_Repositories_Count{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "Repositories"
    }
   ]
  },
  {
   "title": "Scm Statistics",
   "type": "timeseries",
   "description": "Pulls and pushes increase over 5 min",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(com_atlassian_bitbucket_ScmStatistics_Pulls{namespace=\"$namespace\", service=\"$service\"}[5m]))",
     "legendFormat": "Pulls"
    },
    {
     "expr": "sum(increase(com_atlassian_bitbucket_ScmStatistics_Pushes{namespace=\"$namespace\", service=\"$service\"}[5m]))",
     "legendFormat": "Pushes"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\", service=\"$service\"} * 100)",
     "legendFormat": "cpu load ({{ pod }})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"heap\",}/jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"heap\",})",
     "legendFormat": "Used {{ area }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "description": "Rest request processing time by plugin, method and path",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_bitbucket_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"http\",category01=\"rest\",name=\"request\"}",
     "legendFormat": "{{ tag_action }}: {{tag_fromPluginKey}} on {{ tag_path }}"
    }
   ]
  },
  {
   "title": "Hikari Pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_IdleConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "idle ({{ pod }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_ActiveConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "active ({{ pod }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_ThreadsAwaitingConnection{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "awaiting ({{ pod }})"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_bitbucket_TotalConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "total ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate Cached Requests",
   "type": "timeseries",
   "description": "Global number of cached queries successfully retrieved or missed from cache",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "org_hibernate_core_bitbucket_core_QueryCacheHitCount{namespace=\"$namespace\", service=\"$service\", serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\",}",
     "legendFormat": "retrieved from cache ({{ pod }})"
    },
    {
     "expr": "org_hibernate_core_bitbucket_core_QueryCacheMissCount{namespace=\"$namespace\", service=\"$service\", serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "not found in cache ({{ pod }})"
    }
   ]
  },
  {
   "title": "Hibernate Cached Entities",
   "type": "timeseries",
   "description": "Global number of cacheable entities/collections successfully retrieved from the cache or not found in cache and loaded from the database",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "org_hibernate_core_bitbucket_core_SecondLevelCacheHitCount{namespace=\"$namespace\", service=\"$service\", serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "retrieved from cache ({{ pod }})"
    },
    {
     "expr": "org_hibernate_core_bitbucket_core_SecondLevelCacheMissCount{namespace=\"$namespace\", service=\"$service\", serviceRole=\"org.hibernate.stat.Statistics\",serviceType=\"org.hibernate.stat.internal.StatisticsImpl\"}",
     "legendFormat": "not found in cache ({{ pod }})"
    }
   ]
  }
 ]
}