{
 "title": "Bitbucket SSH statistics",
 "description": "Bitbucket uses 'tickets' as a mechanism for creating back-pressure to prevent the system from being overloaded with requests. There are two types of tickets, hosting tickets and command tickets. ",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active session count",
   "type": "timeseries",
   "description": "Number of currently active SSH session",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_ActiveSessionCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} Active session count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Max active session count",
   "type": "timeseries",
   "description": "Highest number of concurrently active SSH sessions since the last startup",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_MaxActiveSessionCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} Max session count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Session created count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been created since the last startup",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionCreatedCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} Session created count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Session closed count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been closed since the last startup\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionClosedCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} Session closed count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Session exception count",
   "type": "timeseries",
   "description": "Total number of SSH sessions that have been terminated because an exception was thrown from the SSH command run\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_bitbucket_SshSessions_SessionExceptionCount{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{name}} Session exception count ({{ pod }})"
    }
   ]
  }
 ]
}