{
 "title": "Bitbucket Webhooks stats",
 "description": "Details relating to Webhooks stats",
 "tags": [ "bitbucket" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "com_atlassian_bitbucket_Repositories_Count"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Publish count",
   "type": "timeseries",
   "description": "A count of the total number of events that could trigger webhooks\n(A publish may create many dispatches)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_PublishCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Publish count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch success count",
   "type": "timeseries",
   "description": "Total number of webhooks to fire successfully with a successful HTTP response(A publish may create many dispatches)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchSuccessCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Success count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch rejected count",
   "type": "timeseries",
   "description": "A count of the number of webhook dispatches that were rejected for execution",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchRejectedCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Rejected count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch last rejected timestamp",
   "type": "timeseries",
   "description": "The last time a webhook was rejected, either from circuit breaking, or due to too many webhooks being in flight",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchLastRejectedTimestamp{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Last rejection ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch in-flight count",
   "type": "timeseries",
   "description": "Total number of dispatches that have been triggered and are awaiting resolution",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchInFlightCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} In-flight count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch failure count",
   "type": "timeseries",
   "description": "Total number of webhooks that fired successfully, but the HTTP response indicates a failure\n(non 2xx code)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchFailureCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Failure count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch error count",
   "type": "timeseries",
   "description": "Total number of webhooks to have had an error while they were being dispatched(non 2xx code)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchErrorCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Error count ({{ pod }})"
    }
   ]
  },
  {
   "title": "Dispatch count",
   "type": "timeseries",
   "description": "Total number of webhooks to have been dispatched",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(com_atlassian_webhooks_Webhooks_DispatchCount{namespace=\"$namespace\", service=\"$service\", endpoint=\"jmx-mesh-sidecar\"}[5m])",
     "legendFormat": "{{name}} Dispatch count ({{ pod }})"
    }
   ]
  }
 ]
}