#!/bin/bash

. /etc/default/nfs-kernel-server
. /etc/default/nfs-common

mkdir /run/sendsigs.omit.d
#service rpcbind start
rpcbind

service nfs-kernel-server start
service nfs-common start

exec inotifywait -m /srv/nfs
