{
 "title": "Bamboo Overview",
 "tags": [ "bamboo" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "java_lang_Memory_HeapMemoryUsage_committed{product=\"bamboo\"}"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "java_lang_Memory_HeapMemoryUsage_committed{product=\"bamboo\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{namespace=\"$namespace\", service=\"$service\"}/1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 19, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=\"$namespace\", service=\"$service\", state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\", service=\"$service\"} * 100)",
     "legendFormat": "cpu load ({{ pod }})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"heap\"}/jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})",
     "legendFormat": "Used {{ area }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} count ({{ pod }})"
    },
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_errorCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} error ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Catalina_ThreadPool_currentThreadCount{namespace=\"$namespace\", service=\"$service\"} / Catalina_ThreadPool_maxThreads{namespace=\"$namespace\", service=\"$service\"}) * 100",
     "legendFormat": "used {{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Catalina_GlobalRequestProcessor_processingTime{namespace=\"$namespace\", service=\"$service\"}[10m]) / increase(Catalina_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Catalina_Manager_activeSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "active on {{context}} ({{ pod }})"
    },
    {
     "expr": "Catalina_Manager_rejectedSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "rejected on {{context}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total and Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_ActiveConnections",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_TotalConnections",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Threads awaiting connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_ThreadsAwaitingConnection",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_2_IdleConnections",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}