{
 "title": "Bitbucket Mesh gRPC",
 "tags": [ "bitbucket-mesh" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "metrics_grpc_Value" } },
   { "name": "service", "query": { "query": "metrics_grpc_Value" } }
  ]
 },
 "panels": [
  {
   "title": "Total Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"calls\",name=\"total\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Running Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"calls\",name=\"running\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Successful Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"calls\",name=\"successful\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Failed Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"calls\",name=\"failed\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "MemoryPool Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"memoryPool\", name=\"used\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "MemoryPool Bytes Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"memoryPool\", name=\"committed\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"memoryPool\", name=\"allocations\"}",
     "legendFormat": "{{size}} (instance)"
    }
   ]
  },
  {
   "title": "Deallocations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_grpc_Value{namespace=\"$namespace\", service=\"$service\", section=\"memoryPool\", name=\"deallocations\"}",
     "legendFormat": "{{size}} (instance)"
    }
   ]
  }
 ]
}