{
 "title": "Bitbucket Mesh Hosting Tickets",
 "tags": [ "bitbucket-mesh" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "metrics_grpc_Value" } },
   { "name": "service", "query": { "query": "metrics_grpc_Value" } }
  ]
 },
 "panels": [
  {
   "title": "Hosting Tickets by Status",
   "type": "timeseries",
   "description": "Limits the number of SCM hosting operations, meaning pushes and pulls, which may be running concurrently. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\", throttledResource=\"scm-hosting\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Git LFS Tickets by Status",
   "type": "timeseries",
   "description": "LFS tickets: Limits the number of Git LFS file transfer operations that may be running concurrently. This is primarily intended to prevent Git LFS requests from consuming all available connections, thereby degrading Git hosting operations.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\", throttledResource=\"git-lfs\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Ref Advertisement Tickets by Status",
   "type": "timeseries",
   "description": "Limits the number of SCM Ref Advertisement operations that may be running concurrently. These are throttled separately from hosting operations as they are much more lightweight and much shorter, so many more of them can run concurrently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\", throttledResource=\"scm-refs\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Command Tickets by Status",
   "type": "timeseries",
   "description": "Limits the number of SCM commands, such as: git diff, git blame, or git rev-list, which may be running concurrently.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\", throttledResource=\"scm-command\"}",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tickets Available by Type",
   "type": "timeseries",
   "description": "Number of tickets currently available for use.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\" ,name=\"available\"}",
     "legendFormat": "{{throttledResource}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tickets Used by Type",
   "type": "timeseries",
   "description": "Number of tickets currently in use.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "metrics_throttling_Value{namespace=\"$namespace\", service=\"$service\", section=\"tickets\" ,name=\"used\"}",
     "legendFormat": "{{throttledResource}} ({{ pod }})"
    }
   ]
  }
 ]
}