{
 "title": "Confluence Cluster Locks",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Cluster Locks Held (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long a database cluster lock was held for. Used by Confluence in a clustered environment.\n\nLock contention can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue. It maybe normal to have a thread holding onto a lock for a long time, if there aren’t any threads waiting for the lock - see db.cluster.lock.waited.duration to find out if there are any threads waiting for the lock.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance,tag_pluginKeyAtCreation,tag_implementation,tag_lockName) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\",tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Locks Waiting (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long a database cluster lock was held for. Used by Confluence in a clustered environment.\n\nLock contention can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue. It maybe normal to have a thread holding onto a lock for a long time, if there aren’t any threads waiting for the lock - see db.cluster.lock.waited.duration to find out if there are any threads waiting for the lock.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance,tag_pluginKeyAtCreation,tag_implementation,tag_lockName) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\",tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active Cluster Locks Held (over time - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long a database cluster lock was held for. Used by Confluence in a clustered environment.\n\nLock contention can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue. It maybe normal to have a thread holding onto a lock for a long time, if there aren’t any threads waiting for the lock - see db.cluster.lock.waited.duration to find out if there are any threads waiting for the lock.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum without(instance,implementation, tag_lockName) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\",tag_statistic=\"active\"})",
     "legendFormat": "{{tag_pluginKeyAtCreation}} "
    }
   ]
  },
  {
   "title": "Active Locks Waiting (over time - cluster wide)",
   "type": "timeseries",
   "description": "Measures how long a database cluster lock was waited for. Used by Confluence in a clustered environment.\n\nIf there many threads waiting for the same lock, it can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum without(instance,implementation, tag_lockName) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"waited\",tag_statistic=\"active\"})",
     "legendFormat": "{{tag_pluginKeyAtCreation}}"
    }
   ]
  },
  {
   "title": "Most locks held (cluster wide)",
   "type": "table",
   "description": "* Average heavily weights timers from the last 5 minutes\n\nMeasures how long a database cluster lock was held for. Used by Confluence in a clustered environment.\n\nIf there many threads waiting for the same lock, it can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by (tag_lockName, tag_pluginKeyAtCreation) (com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\"})"
    },
    {
     "expr": "sum by (tag_lockName, tag_pluginKeyAtCreation) (com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\"})"
    },
    {
     "expr": "max by (tag_lockName, tag_pluginKeyAtCreation)  (com_atlassian_confluence_metrics_99thPercentile{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"held\"})"
    }
   ]
  },
  {
   "title": "Most locks waited (cluster wide)",
   "type": "table",
   "description": "* Average heavily weights timers from the last 5 minutes\nMeasures how long a database cluster lock was waited for. Used by Confluence in a clustered environment.\n\nIf there many threads waiting for the same lock, it can lead to performance degradation. Contact the vendor responsible to flag and investigate the issue.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg by (tag_lockName, tag_pluginKeyAtCreation) (com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"waited\"})"
    },
    {
     "expr": "sum by (tag_lockName, tag_pluginKeyAtCreation) (com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"waited\"})"
    },
    {
     "expr": "max by (tag_lockName, tag_pluginKeyAtCreation)  (com_atlassian_confluence_metrics_99thPercentile{namespace=\"$namespace\", service=\"$service\", category00=\"cluster\",category01=\"lock\",category02=\"waited\"})"
    }
   ]
  }
 ]
}