{
 "title": "Confluence Database Load",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Relative load by API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Using AO EntityManager (mean - cluster wide)",
     "type": "timeseries",
     "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(avg without (instance, tag_entityType) (com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", category02=\"entityManager\"}))",
       "legendFormat": "{{tag_invokerPluginKey}} - {{name}}"
      }
     ]
    },
    {
     "title": "Load Using AO EntityManager (p99 - cluster wide)",
     "type": "timeseries",
     "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "topk(5, (max without(instance) (com_atlassian_confluence_metrics_99thPercentile{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", category02=\"entityManager\"})))",
       "legendFormat": "{{tag_invokerPluginKey}} - {{name}} - {{tag_entityType}}"
      }
     ]
    },
    {
     "title": "Cumulative Count Using AO's EntityManager (cluster wide)",
     "type": "timeseries",
     "description": "Measures the total count of AO operations (create, find, delete, deleteWithSQL, get, stream, count) by the plugins.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance, tag_entityType) (com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", category02=\"entityManager\"})",
       "legendFormat": "{{tag_invokerPluginKey}} - {{name}} "
      }
     ]
    }
   ]
  },
  { "title": "AO's executeInTransaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Load via AO's executeInTransaction (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via AO's executeInTransaction (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))) /\n(sum without (instance, tag_taskName) (delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Cumulative count using AO's executeInTransaction (cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName) (com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"})",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via AO's executeInTransaction (p99)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_99thPercentile{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}",
     "legendFormat": "{{tag_invokerPluginKey}} - {{tag_taskName}}"
    }
   ]
  },
  {
   "title": "Total active operations running  via AO's executeInTransaction (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active operations running via AO's executeInTransaction (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an AO transaction takes, when executed inside the TransactionCallBack. This is mainly used by Confluence plugins.\n\nThe transaction can have many AO operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"ao\",name=\"executeInTransaction\", tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "SAL's transactionalExecutor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Load via SAL's transactionalExecutor (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}) * \n(delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}[5m]))))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via SAL's transactionalExecutor (mean last 5 minutes - cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "# We do this because the average of averages is not the real average. We must weigh them by the count\n(sum without (instance, tag_taskName) ((com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}) * \n(delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))) /\n(sum without (instance, tag_taskName) (delta(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"ao\", name=\"executeInTransaction\"}[5m])))\n",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Cumulative count using SAL's transactionalExecutor (cluster wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName) (com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"})",
     "legendFormat": "{{tag_invokerPluginKey}}"
    }
   ]
  },
  {
   "title": "Operation times via SAL's transactionalExecutor (p99)",
   "type": "timeseries",
   "description": "Measures how long an AO operation (create, find, delete, deleteWithSQL, get, stream, count) that uses the Entity Manager takes.\n\nThe operation query might be long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_99thPercentile{namespace=\"$namespace\", service=\"$service\", category00=\"db\", category01=\"sal\", name=\"transactionalExecutor\"}",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  {
   "title": "Total active operations running  via SAL's transactionalExecutor (current - cluster wide)",
   "type": "gauge",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_taskName, tag_invokerPluginKey) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\", tag_statistic=\"active\"})"
    }
   ]
  },
  {
   "title": "Active operations using SAL's transactionalExecutor (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an SAL transaction takes, when executed inside the DefaultTransactionalExecutor.\n\nThe transaction can have many SAL operations, it can be either there are too many operations or the query is long running, or the database is under load. Contact the vendor responsible and investigate if long running queries are expected.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"sal\",name=\"transactionalExecutor\",tag_statistic=\"active\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  },
  { "title": "AO upgrade tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "AO Upgrade Tasks (current - active count)",
   "type": "gauge",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, tag_fromPluginKey, tag_taskName) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"ao\",name=\"upgradeTask\",tag_statistic=\"active\",tag_subCategory=\"current\"})"
    }
   ]
  },
  {
   "title": "AO Upgrade Tasks (over time - active count)",
   "type": "timeseries",
   "description": "Measures how long an App is taking to upgrade a part of the data that it stores in the database.\n\nUpgrade tasks happen when an App is both updated and enabled, during this time the App’s functionality will probably be unavailable, and it may temporarily increase load on the database and the node the upgrade task is running on.\n\nIf an App stores a lot of data in database then this may take a while to run, if possible, try to schedule upgrading Apps with large amounts of data in off-peak hours.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum without (instance) (com_atlassian_confluence_metrics_Value{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"ao\",name=\"upgradeTask\",tag_statistic=\"active\",tag_subCategory=\"current\"})",
     "legendFormat": "{{ tag_invokerPluginKey }} - {{tag_taskName}} (task)"
    }
   ]
  }
 ]
}