{
 "title": "Confluence Hikari Connection Pool",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "Active hikari pool connections",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_1_ActiveConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "description": "Total connections in hikari pool",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_1_TotalConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "description": "Idle connections in hikari pool",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_1_IdleConnections{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Threads Awaiting Connection",
   "type": "timeseries",
   "description": "Waiting connections",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_zaxxer_hikari_Pool_HikariPool_1_ThreadsAwaitingConnection{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}