{
 "title": "Confluence Overview",
 "tags": [ "confluence" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "Confluence_MailTaskQueue_ErrorQueueSize"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Pid{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_Uptime{namespace=\"$namespace\", service=\"$service\"}/1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Available CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Blocked Threads",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_threads_state{namespace=\"$namespace\", service=\"$service\", state=\"BLOCKED\"}",
     "legendFormat": "{{ state }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionTime{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(java_lang_OperatingSystem_ProcessCpuLoad{namespace=\"$namespace\", service=\"$service\"} * 100)",
     "legendFormat": "cpu load ({{ pod }})"
    }
   ]
  },
  {
   "title": "Heap Used %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", area=\"heap\"}/jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", area=\"heap\"})",
     "legendFormat": "Used {{ area }} ({{ pod }})"
    }
   ]
  },
  {
   "title": "GC Pauses",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"jvm\", category01=\"gc\"}",
     "legendFormat": "{{ pod }} - {{tag_cause}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(java_lang_G1_Old_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Old_Generation ({{ pod }})"
    },
    {
     "expr": "increase(java_lang_G1_Young_Generation_CollectionCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "G1_Young_Generation ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tomcat Request Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} count ({{ pod }})"
    },
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_errorCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} error ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(Standalone_ThreadPool_currentThreadCount{namespace=\"$namespace\", service=\"$service\"} / Standalone_ThreadPool_maxThreads{namespace=\"$namespace\", service=\"$service\"}) * 100",
     "legendFormat": "used {{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(Standalone_GlobalRequestProcessor_processingTime{namespace=\"$namespace\", service=\"$service\"}[10m]) / increase(Standalone_GlobalRequestProcessor_requestCount{namespace=\"$namespace\", service=\"$service\"}[10m])",
     "legendFormat": "{{name}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Tomcat Sessions",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Standalone_Manager_activeSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "active sessions: {{context}} ({{ pod }})"
    },
    {
     "expr": "Standalone_Manager_rejectedSessions{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "rejected sessions: {{context}} ({{ pod }})"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_atlassian_confluence_metrics_Mean{namespace=\"$namespace\", service=\"$service\", category00=\"db\",category01=\"connection\",category02=\"latency\",name=\"statistics\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Database Reads / Writes",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"postgres\",name=\"reads\"}[10m])",
     "legendFormat": "reads ({{ pod }})"
    },
    {
     "expr": "rate(com_atlassian_confluence_metrics_Count{namespace=\"$namespace\", service=\"$service\", category00=\"postgres\",name=\"writes\"}[10m])",
     "legendFormat": "writes ({{ pod }})"
    }
   ]
  }
 ]
}